language: go

sudo: false

go:
  - 1.7beta1
  - tip

services:
  - memcached
  - redis-server

addons:
  apt:
    packages:
      - graphicsmagick

before_install:
  - go get -v github.com/alecthomas/gometalinter && gometalinter --install

install: go get -v -d -t ./...

script:
  - "echo 'mode: atomic' > coverage.txt && go list ./... | xargs -n1 -I{} sh -c 'go test -v -covermode=atomic -coverprofile=coverage.tmp {} && tail -n +2 coverage.tmp >> coverage.txt' && rm coverage.tmp"
  - gometalinter -E gofmt -D gotype -D vetshadow -D dupl -D goconst -D interfacer -D gocyclo --tests --deadline=10m ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
